### ISSUE TITLE
.env file needed to reset password

### ISSUE THREAD

**Issue by Gothsec** [Gothsec/StockIn#8]
![image](https://github.com/user-attachments/assets/c985df20-3cbf-4292-abd4-29df55b907ce)

For security reasons of not entering the email and password of the email that sends the recovery link/code we must use an .env file which I will pass to you privately for you to test.

I'm still looking for the best way to do the backend, but it's more complicated than I thought, it may take me longer than expected.

**Comment by 1Orchestratooor1** [comment]
Understood, it's better to prevent than to regret.

**Comment by Gothsec** [comment]
![image](https://github.com/user-attachments/assets/d882d8d8-370f-41f5-8f7d-2fc32e173a78)

![image](https://github.com/user-attachments/assets/bf3f8ccb-a6d4-4f73-9d77-ed393b1db89e)

Now is sending the email, but the link doesn't work rn, trying to figure out the token validation, appreciate ideas

**Comment by 1Orchestratooor1** [comment]
What do you mean by token validation? Do you want to create and send a token to the user by email, and that token is used on the page where the new password will be entered? 🤔

**Comment by Gothsec** [comment]
I mean, the token validation is to set into the link to be 1 of 1 unique link that expires in 1 hour, I just need to create the reset-password view and validate the token before set the new password, by now, this task is in stand by

**Comment by garaven** [comment]
Done ✔
